name: cvenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - hdf5
  - libopencv
  - numpy
  - opencv
  - pillow
  - pip
  - py-opencv
  - python
  - pytorch
  - qt
  - tensorboard
  - torchvision